spring.application.name=secretaria

spring.datasource.url=jdbc:postgresql://localhost:1804/Secretaria
spring.datasource.username=${DB_USERNAME:MrRDF}
spring.datasource.password=${DB_PASSWORD:MrRDF180402}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

api.security.token.secret=${JWT_SECRET:secretaria_chave_secreta_123}